### ISSUE TITLE
Using all observations after the pipeline for downstream analysis

### ISSUE THREAD

**Issue by K-Mulder** [KyleFerchen/pyInfinityFlow#3]
Hello, 

I am trying to run the pyInfinityFlow pipeline and want to have all the observations. 
It seems with the settings there is no clear option to have all the observations after running the pipeline. 
Would you recommend to increase the ratio_for_vaildation to 1.0?

Current settings:
pyInfinityFlow --data_dir /... \
                --out_dir /output \
                --backbone_annotation backbone_selection_file.csv \
                --infinity_marker_annotation test.csv \
                --random_state 7 \
                --use_logicle_scaling True \
                --normalization_method "zscore" \
                --n_events_train 0 \
                --n_events_validate 0 \
                --ratio_for_validation 0.3 \
                --separate_backbone_reference None \
                --n_events_combine 0 \
                --n_final 0 \
                --add_umap True \
                --find_clusters True \
                --find_markers True \
                --make_feature_plots True \
                --use_pca True \
                --n_pc 15 \
                --n_pc_plot_qc 50 \
                --save_h5ad True \
                --save_feather True \
                --save_file_handler True \
                --save_regression_models True \
                --verbosity 1 \
                --n_cores 40

Thank you for your help

Kevin

**Comment by KyleFerchen** [comment]
Hello!

By "have all the observations after running the pipeline" I assume you mean the number of events in the output InfinityFlow Object .fcs file.

The `--n_events_combine 0` parameter is meant to tell the program to use all of the events from all of the InfinityMarker files to pool together. So for each input .FCS file, all events will be taken, with their backbone features, and the InfinityMarker values will be imputated across all observations. So by including this, you should be getting all cells from every input file in the final FCS output file.

Are you seeing fewer events in the final InfinityFlow Object than expected when you run the command? - If that is the case I will try to debug issues that prevent the expected behavior

The `--ratio_for_validation` doesn't apply to the final output object. This parameter is used for the purpose of building/validating the regression models. It is the ratio of observations that are withheld from regression model fitting. The purpose of these events is to test how well the regression model could predict the true value. Because these events were not used to build the model, it provides an unbiased input from which we can take the predicted InfinityMarker value, and calculate how far off it is from the real recorded value. I would recommend not increasing this above 0.5 (50% of the cells withheld). This is because I would prefer to give the model more information to help make it more accurate. This is especially important if you have a lot of rare cell populations in your sample. You want to try to have enough cells to fit the model to describe all of the cell populations in your sample. I would say it is more common to use 20% of the data for validation and 80% for model fitting (`--ratio_for_validation 0.2`). However, since the original InfinityFlow package had used a default of 50% for each, I had used that in the documentations example.

**Comment by K-Mulder** [comment]
Hello, 

Thank you for the response!
I ran my analysis with the settings I shared and got a subset of cells as an output of the pipeline. 
My original amount of cells combined is 24988815 
When I ran with these settings, it gave 8036977 cells. 

So with this, it feels as if it took the ratio of cells that I stated in  --ratio_for_validation  0.3

**Comment by KyleFerchen** [comment]
I see. The program is only pooling from the validation set then.
I can add in an option to take cells from both the validation and fitting data sets, but it will take a little time.

An alternative approach you can take now would be to pool all of your input data into one FCS file. Then use this concatenated file for the `--separate_backbone_reference`. I think most FCS analysis software (Eg. Flowjo) can concatenate FCS files, as long as the channel names are the same for the backbone markers.
Would you try this approach?

**Comment by K-Mulder** [comment]
Hello, 

It seems that I am running into a error if I try to use the reference. 
pyInfinityFlow --data_dir /mnt/
                --out_dir /mnt/  \
                --backbone_annotation /mnt.csv \
                --infinity_marker_annotation .csv \
                --random_state 7 \
                --use_logicle_scaling True \
                --normalization_method "zscore" \
                --n_events_train 0 \
                --n_events_validate 0 \
                --ratio_for_validation 0 \
                --separate_backbone_reference /mnt/beegfs/userdata/k_mulder/PBMC_Legendscreen/run_3/concat_Fj_Legendscreen_3_1.fcs \
                --n_events_combine 0 \
                --n_final 0 \
                --add_umap True \
                --find_clusters True \
                --find_markers True \
                --make_feature_plots True \
                --use_pca True \
                --n_pc 15 \
                --n_pc_plot_qc 50 \
                --save_h5ad True \
                --save_feather True \
                --save_file_handler True \
                --save_regression_models True \
                --verbosity 1 \
                --n_cores 20


This gives the following error: 
Running InfinityFlow from single directory, with all input .fcs files using the same channels for backbone...
Traceback (most recent call last):
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/bin/pyInfinityFlow", line 8, in <module>
    sys.exit(main())
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/lib/python3.8/site-packages/pyInfinityFlow/pyInfinityFlow.py", line 204, in main
    raise ValueError("separate_backbone_reference and n_events_combine can not be "\
ValueError: separate_backbone_reference and n_events_combine can not be used together. One must be None.


And then replaced with none it gives the following error: 
usage: pyInfinityFlow [-h] --data_dir DATA_DIR --out_dir OUTPUT_DIR
                      --backbone_annotation BACKBONE_ANNOTATION_FILE
                      --infinity_marker_annotation
                      INFINITY_MARKER_ANNOTATION_FILE
                      [--random_state RANDOM_STATE]
                      [--use_logicle_scaling USE_LOGICLE_SCALING]
                      [--normalization_method NORMALIZATION_METHOD]
                      [--n_events_train N_EVENTS_TRAIN]
                      [--n_events_validate N_EVENTS_VALIDATE]
                      [--ratio_for_validation RATIO_FOR_VALIDATION]
                      [--separate_backbone_reference SEPARATE_BACKBONE_REFERENCE]
                      [--n_events_combine N_EVENTS_COMBINE]
                      [--require_n_events_combine REQUIRE_N_EVENTS_COMBINE]
                      [--n_final N_FINAL] [--add_umap ADD_UMAP]
                      [--find_clusters FIND_CLUSTERS]
                      [--find_markers FIND_MARKERS]
                      [--make_feature_plots MAKE_FEATURE_PLOTS]
                      [--use_pca USE_PCA] [--n_pc N_PC]
                      [--n_pc_plot_qc N_PC_PLOT_QC] [--save_h5ad SAVE_H5AD]
                      [--save_feather SAVE_FEATHER]
                      [--save_file_handler SAVE_FILE_HANDLER]
                      [--save_regression_models SAVE_REGRESSION_MODELS]
                      [--verbosity VERBOSITY] [--n_cores N_CORES]
pyInfinityFlow: error: argument --n_events_combine: invalid int value: 'None'

**Comment by KyleFerchen** [comment]
For now, can you simply remove the argument `--n_events_combine`
It should default to None type if you don't try to specify any option.
I'll look into how the argument is being parsed currently so that it supports using 'None' as a string argument.

**Comment by K-Mulder** [comment]
When I remove this comment --n_events_combine
It gives still the following error: 

Running InfinityFlow from single directory, with all input .fcs files using the same channels for backbone...
Traceback (most recent call last):
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/bin/pyInfinityFlow", line 8, in <module>
    sys.exit(main())
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/lib/python3.8/site-packages/pyInfinityFlow/pyInfinityFlow.py", line 204, in main
    raise ValueError("separate_backbone_reference and n_events_combine can not be "\
ValueError: separate_backbone_reference and n_events_combine can not be used together. One must be None.


With the following arguments: 

source activate pyInfinityFlow

pyInfinityFlow --data_dir /mnt/fcs/ 
                --out_dir /output \
                --backbone_annotation /mnt/backbone_selection_file.csv \
                --infinity_marker_annotation /mnt/test.csv \
                --random_state 7 \
                --use_logicle_scaling True \
                --normalization_method "zscore" \
                --n_events_train 0 \
                --n_events_validate 0 \
                --ratio_for_validation 0 \
                --separate_backbone_reference /mnt/concat_Fj_Legendscreen_3_1.fcs \
                --n_final 0 \
                --add_umap True \
                --find_clusters True \
                --find_markers True \
                --make_feature_plots True \
                --use_pca True \
                --n_pc 15 \
                --n_pc_plot_qc 50 \
                --save_h5ad True \
                --save_feather True \
                --save_file_handler True \
                --save_regression_models True \
                --verbosity 1 \
                --n_cores 20

**Comment by KyleFerchen** [comment]
I noticed that the default value for --n_events_combine was adjusted and that caused this issue with the failed separate_backbone_reference. 

I fixed this and reuploaded the package.
Can you please try to reinstall the package and see if running the above command works with this fix?

**Comment by K-Mulder** [comment]
Hello, 

I am not sure why but currently it does not want to detect the individual files. 
/var/spool/slurmd/job4645016/slurm_script: line 7: activate: No such file or directory


Running InfinityFlow from single directory, with all input .fcs files using the same channels for backbone...
Isotype controls detected. Will attempt to use background correction...
Traceback (most recent call last):
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/lib/python3.8/site-packages/pyInfinityFlow/InfinityFlow_Utilities.py", line 911, in check_infinity_flow_annotation_dataframes
    raise ValueError("\tratio_for_validation must be between "\
ValueError: 	ratio_for_validation must be between 0 and 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/bin/pyInfinityFlow", line 8, in <module>
    sys.exit(main())
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/lib/python3.8/site-packages/pyInfinityFlow/pyInfinityFlow.py", line 219, in main
    file_handler = check_infinity_flow_annotation_dataframes(backbone_annotation=backbone_annotation, 
  File "/mnt/beegfs/merfish/.conda/envs/pyInfinityFlow/lib/python3.8/site-packages/pyInfinityFlow/InfinityFlow_Utilities.py", line 1000, in check_infinity_flow_annotation_dataframes
    raise ValueError("File reading error. Could not set up FileHandler for"\
ValueError: File reading error. Could not set up FileHandler for  file A1_Blank.fcs.

The input is still the same as before.

**Comment by KyleFerchen** [comment]
Can you try to remove the --ratio_for_validation option, or set it to a low value > 0.0?

It will default to use 20% (0.2) of the data from each InfinityMarker file to use as validation for the regression model. A value of 0 is throwing the error. I would suggest to try 0.05 or 0.1 if you want to use lower than 0.2.
